### ISSUE TITLE
Is it free to use on the Website?

### ISSUE THREAD

**Issue by PierrunoYT** [e2b-dev/fragments#60]
Is it free to use on the Website?

**Comment by mishushakov** [comment]
Can you please clarify what you mean?

**Comment by PierrunoYT** [comment]
> Can you please clarify what you mean?

I mean the Demo Link.  Do we need to add our own API Key? Or better why is there a hosted Demo and a local one?

**Comment by mishushakov** [comment]
We provide a hosted version on fragments.e2b.dev, which should also work locally when you're building from source (this repo)
