### ISSUE TITLE
An unexpected error has occurred. Please try again

### ISSUE THREAD

**Issue by Jekumana** [e2b-dev/fragments#75]
I'm encountering a persistent error when using your platform. Whenever I attempt to enter text in a dialog box, I receive the following message: "An unexpected error has occurred. Please try again."

This issue is preventing me from effectively using the platform. Please let me know if there's a solution or if you require further information.

Thank you for your assistance.

**Comment by mishushakov** [comment]
Try selecting a different model or come back sometime later, we're rate-limiting requests.
