### ISSUE TITLE
Preview section not working

### ISSUE THREAD

**Issue by akasaka99** [e2b-dev/fragments#76]
Hi, the Preview section does not work (spinning arrow) whereas the Code section is generated without issue. 
I've tried with several models and several browsers FF, chrome and Safari, the Code always work but the Preview never works.
Are there any settings which are required to have on to have the Preview working?
Thanks

**Comment by mishushakov** [comment]
are you using the hosted version (fragments.e2b.dev) or are you self-hosting?

**Comment by akasaka99** [comment]
I am using the web version on fragments.e2b.dev.
PS: As shown in the picture, the Preview is greyed out with spinning wheel, not using any extension.
![Screen Shot 2024-10-14 at 19 18 51](https://github.com/user-attachments/assets/9549a776-03d5-4eff-88b1-3b880ef77d21)

**Comment by mlejva** [comment]
@akasaka99 it looks like you're generating Dart code. Fragments don't support that at the moment

**Comment by akasaka99** [comment]
Ah ok just saw the supported frameworks. Thanks
